FROM alpine
LABEL MAINTAINER m120

WORKDIR /work

# INSTALL: pkg
RUN apk --update add \
  tzdata nginx && \
  rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*

# ADD: Configs
ADD ./nginx.conf /etc/nginx/nginx.conf
ADD ./run.sh ./

# SETTING:
RUN set -x && \
    adduser -D -g 'www' www && \
    install -o www -g www -d /var/lib/nginx && \
    install -o www -g www -d /www && \
    install -o www -g www -d /var/tmp/nginx && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

STOPSIGNAL SIGTERM

CMD ["/bin/sh", "run.sh"]